"""create_tenders_table

Revision ID: 0ce92258c071
Revises: None
Create Date: 2026-06-06 14:28:41.825849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce92258c071'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_number', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('tender_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'DOWNLOADED', 'PARSED', 'FAILED', name='tender_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_created_at'), 'tenders', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenders_department'), 'tenders', ['department'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_tender_number'), 'tenders', ['tender_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_tender_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_department'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_created_at'), table_name='tenders')
    op.drop_table('tenders')
    # ### end Alembic commands ###
