"""create_documents_and_history_tables

Revision ID: 624387f57cfa
Revises: 0ce92258c071
Create Date: 2026-06-06 14:45:26.915563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624387f57cfa'
down_revision: Union[str, None] = '0ce92258c071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_history_tender_id'), 'download_history', ['tender_id'], unique=False)
    op.create_table('tender_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_documents_sha256_hash'), 'tender_documents', ['sha256_hash'], unique=True)
    op.create_index(op.f('ix_tender_documents_tender_id'), 'tender_documents', ['tender_id'], unique=True)
    op.alter_column('tenders', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tenders', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('NEW', 'DOWNLOADING', 'DOWNLOADED', 'FAILED', name='tender_status_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenders', 'status',
               existing_type=sa.Enum('NEW', 'DOWNLOADING', 'DOWNLOADED', 'FAILED', name='tender_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('tenders', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tender_documents_tender_id'), table_name='tender_documents')
    op.drop_index(op.f('ix_tender_documents_sha256_hash'), table_name='tender_documents')
    op.drop_table('tender_documents')
    op.drop_index(op.f('ix_download_history_tender_id'), table_name='download_history')
    op.drop_table('download_history')
    # ### end Alembic commands ###
