from decimal import Decimal
from typing import List
from pydantic import BaseModel, Field, UUID4


class AnalystRequest(BaseModel):
    annual_turnovers: List[Decimal] = Field(
        ...,
        description="List of turnovers for preceding financial years"
    )
    net_worth: Decimal = Field(
        ...,
        description="Net worth of the bidder"
    )
    eligibility_rules: List[str] = Field(
        default_factory=list,
        description="Eligibility criteria rules to check matching against"
    )


class AnalystResponse(BaseModel):
    tender_id: UUID4 = Field(..., description="UUID of the analyzed tender")
    recommendation: str = Field(..., description="The calculated rule-based recommendation (GO/REVIEW/NO_BID)")
    win_probability: float = Field(..., description="Win probability percentage (0 to 100)")
    executive_summary: str = Field(..., description="Narrative executive summary generated by AI")
    management_brief: str = Field(..., description="Management brief detailing metrics and actions")
    eligibility_explanation: str = Field(..., description="Explanation of eligibility and project matching results")
    risk_explanation: str = Field(..., description="Detailed explanation of compliance risks and mitigations")
    bid_recommendation_narrative: str = Field(..., description="Detailed narrative explaining the final decision")
